context.objects = [
    {
        factory = adapter
        args = {
            factory.name   = support.null-audio-sink
            node.name      = "combined"
            node.description = "Combined Recording Sink"
            media.class    = "Audio/Sink"
            audio.position = [ FL FR ]
            monitor.channel-volumes = true
            monitor.passthrough = true
        }
    }
]
